### ISSUE TITLE
The TwigLoader should inject a {% line %} tag to preserve line numbers in errors

### ISSUE THREAD

**Issue by stof** [webuni/front-matter#9]
Twig supports a special `{% line %}` tag (which is undocumented IIRC, but it exists since before Twig 1.0.0), which allows to override the line numbering (the line on which the tag is set gets considered as re-numbered (and so all following lines too). This would allow to preserve original line numbers in error messages even when the frontmatter is removed:

```
---
some: frontmatter
---
{# Beginning of content line 4 of the file #}
```

would become

```twig
{% line 3 %}
{# Beginning of content line 4 of the file #}
```

This makes debugging a lot easier when line numbers in the file correspond to the source file rather than the file without the frontmatter.

**Comment by localheinz** [comment]
@stof 

Quick question, have you gotten parsing of front matter to work?

I have been fiddling around with Twig to achieve the following:

- store front matter in Twig templates
- merge context passed to `render()` with data from front matter stored in Twig templates

However, this does not appear to be so easy:

- If you want to use the `LintCommand` to lint Twig templates with front matter, you have to copy, adjust, and eventually replace the entire `LintCommand` to allow for manipulating the `$template` because the `validate()` method in the `LintCommand` is `private`. You also have to replace the native filesystem loader with the front matter loader from this package here. Here we need to ignore the front matter, otherwise the tokenizer chokes on the front matter, but we also need to inject the `{% line%}` marker (:+1:) to allow for better debugging
- If you want to merge the context passed to `render()` with data from front matter stored in Twig templates, that appears to be another can of worms to me.

Have you gotten anything similar to above to work?

**Comment by stof** [comment]
@localheinz I'm not using front matters myself in my templates. I commented here because I provided answers in the issues discussing the feature request in Twig itself

**Comment by localheinz** [comment]
@stof 

Thank you!

Is [this](https://github.com/twigphp/Twig/issues/2440) the issue?

**Comment by stof** [comment]
@localheinz yes (or at least one of them, I don't remember if there was other duplicates)

**Comment by hason** [comment]
@stof Thanks for the suggestion! It is implemented in the master branch.

@localheinz You can now inject the front matter as variables into Twig template, see https://github.com/webuni/front-matter#twig-loader.
